export const Categories = {
  TOP: 'top',
  NEW: 'new',
  SLOTS: 'slots',
  JACKPOTS: 'jackpots',
  LIVE: 'live',
  BLACKJACK: 'blackjack',
  ROULETTE: 'roulette',
  TABLE: 'table',
  POKER: 'poker',
  OTHER: 'other',
  BALL: 'ball',
  VIRTUAL: 'virtual',
  FUN: 'fun',
};
